### ISSUE TITLE
Download SugarRecord without Realm

### ISSUE THREAD

**Issue by iOSBeginners** [pepibumur/SugarRecord#191]
Hello,

I want to download and use SugarRecord without Realm because you have the version 1.0.0 of Realm and my framework use another version of Realm that is why i want to remove Realm from SugarRecord

Is is possible to remove Realm from SugarRecord with Cocoapods because i'm using it.

Best regards,

**Comment by pepibumur** [comment]
If you are using CocoaPods you can specify the subspec that you want:

```ruby
pod "SugarRecord/Realm"
pod "SugarRecord/CoreData"
pod "SugarRecord/Foundation"
```
Depending on the subspec you choose CocoaPods will integrate wether a framework or another. Try it out and let me know if it helped.
