### ISSUE TITLE
CocoaPods versio 2.2.1

### ISSUE THREAD

**Issue by Koranda** [pepibumur/SugarRecord#201]
When install sugar record 2.2.1 to iOS application, cocoapods return error.  

The platform of the target `xxxx` (iOS 8.0) is not compatible with `SugarRecord/CoreData (2.2.1)`, which does not support `ios`.

**Comment by VladislavJevremovic** [comment]
True, I get this also:

[!] The platform of the target `XXXXX` (iOS 8.3) is not compatible with `SugarRecord/CoreData (2.2.1)`, which does not support `ios`.

On a side note, if I drop to 2.1.9, it works, but Realm frameworks are still present - is this expected?

**Comment by pepibumur** [comment]
Are you using Carthage?

**Comment by VladislavJevremovic** [comment]
No, not at all, pods only.

```
platform :ios, '8.3'
use_frameworks!

target 'XXXXX' do

pod 'SugarRecord/CoreData', '2.2.1'

end
```

**Comment by pepibumur** [comment]
@VladislavJevremovic &@Koranda , it should be solved in 2.2.2
https://github.com/pepibumur/SugarRecord/pull/203

**Comment by VladislavJevremovic** [comment]
Thanks a bunch, works like a charm now! Cheers!

**Comment by Koranda** [comment]
Thanks, it works greate

**Comment by pepibumur** [comment]
Nice, thanks for reporting :)
