### ISSUE TITLE
Context save errors silenced

### ISSUE THREAD

**Issue by VladislavJevremovic** [pepibumur/SugarRecord#204]
In `CoreDataDefaultStorage.operation` you have `_ = try? context.save()` which effectively silences any errors happening on save.

It's just that you're not sure the save actually succeeded and debug value is lost, I guess.

**Comment by pepibumur** [comment]
Good catch @VladislavJevremovic I'll try to expose these errors instead of silencing them.

**Comment by pepibumur** [comment]
https://github.com/pepibumur/SugarRecord/commit/d3295570677d3da38b210e3af3aeea5593fcb150
