### ISSUE TITLE
Entity Class with custom prefix

### ISSUE THREAD

**Issue by Koranda** [pepibumur/SugarRecord#206]
Hello, it would be possible to modify your implementation

```
extension NSManagedObject {
    public static var entityName: String {
        get {
            return NSStringFromClass(self).componentsSeparatedByString(".").last!
        }
    }
}
```

which would apply **class** instead of **static** ? For the class of entities I use the prefix. If the property is static, so I can implement
	
```
extension QeUser {
  public override class var entityName: String {
    get {
      return "User"
    }
  }
}
```
Or would have been nice opportunity register own prefix classes.

Thanks

**Comment by pepibumur** [comment]
https://github.com/pepibumur/SugarRecord/commit/8685d1391688314b7b23b4c4411ecbf1fcc90e37
