### ISSUE TITLE
Is the rootSavingContext save in the right thread?

### ISSUE THREAD

**Issue by RoCry** [pepibumur/SugarRecord#212]
```swift
public func operation(operation: (context: Context, save: () -> Void) -> Void) {
    let context: NSManagedObjectContext = self.saveContext as! NSManagedObjectContext
    context.performBlockAndWait {
        var save: Bool = false
        operation(context: context, save: { save = true })
        if save {
            _ = try? context.save()
            if self.rootSavingContext.hasChanges {
                _ = try? self.rootSavingContext.save()
            }
        }
    }
}
```

Say you are operating in different thread at the same time, then the self.rootSavingContext.save() will save in different private queue.

Is it better to wrap the `self.rootSavingContext.save()` inside performBlock?

**Comment by jhoughjr** [comment]
I think i could be seeing this issue as well. When I try to add a relationship inside of an operation it crashes due to objects being in different contexts. Im not sure what is going on since heroics say everything is propagated across contexts.

**Comment by pepibumur** [comment]
@RoCry are you having problems because the rootSavingContext is saved from a different thread? It shouldn't be a problem.

**Comment by RoCry** [comment]
@pepibumur Sometimes I got ``UNIQUE constraint failed`` error at ``_ = try? self.rootSavingContext.save()``, it would be all right if I put the root saving code in performBlock and performBlockAndWait.

I will add a test case to reproduce this when I have time.

**Comment by pepibumur** [comment]
Would be cool @RoCry , thanks for reporting it btw

**Comment by RoCry** [comment]
@pepibumur Forgive me that I didn't add test case for this, cause I can't make the tests work.
But I did reproduced this in the sample project. Just need to change a few lines. 

replace the code
```swift
func userDidSelectAdd(sender: AnyObject!) {
    db.operation { (context, save) -> Void in
        let _object: BasicObject = try! context.new()
        _object.date = NSDate()
        _object.name = randomStringWithLength(10) as String
        try! context.insert(_object)
        save()
    }
    updateData()
}
```

to

```swift
func userDidSelectAdd(sender: AnyObject!) {
    insertMultiRow {
        self.updateData()
    }
}

private func insertMultiRow(completion: () -> ()) {
    let group = dispatch_group_create()
    
    for _ in 0..<10 {
        dispatch_group_enter(group)
        
        dispatch_async(dispatch_get_global_queue(QOS_CLASS_BACKGROUND, 0)) {
            self.db.operation { (context, save) -> Void in
                let _object: BasicObject = try! context.new()
                _object.date = NSDate()
                _object.name = randomStringWithLength(10) as String
                try! context.insert(_object)
                save()
            }
            
            dispatch_group_leave(group)
        }
    }
    
    dispatch_group_notify(group, dispatch_get_main_queue()) {
        self.updateData()
    }
}
```

Then you could get this error:
![image](https://cloud.githubusercontent.com/assets/1117026/13454595/2a05553e-e093-11e5-87be-dfc88b03fa07.png)

**Comment by pepibumur** [comment]
@RoCry Thank's for reporting. I'll try to reproduce it and fix it.

**Comment by pepibumur** [comment]
https://github.com/pepibumur/SugarRecord/commit/0cc13d4e186b85b8aba668251006079f99486bd2
