### ISSUE TITLE
ReactiveExtension improvements

### ISSUE THREAD

**Issue by startupthekid** [pepibumur/SugarRecord#216]
I built my own ReactiveCocoa extensions for SugarRecord (because I'm using Moya and their dependency is 4.0.0 while SugarRecord's is 4.0.1 so I have to wait for Moya to update) and I had some ideas for improvements to the ReactiveCocoa extensions.

1) Remove `ReactiveStorage` protocol and just extend Storage directly.

`ReactiveStorage` seems a bit superfluous and it was unclear how to make a `RealmDefaultStorage` object that conformed to both `Storage` and `ReactiveStorage` without making a stub subclass so what I did is:

```swift
extension Storage {
    func operation(operation: (context: Context, save: Saver) -> Void) -> SignalProducer<Void, NoError> {}
}
```

Because `Storage` is being extended, `Saver` can be safely used since that's where it's defined without having to redefine it in ReactiveStorage.

2) Have the operation block throw an error

One of the benefits of using ReactiveCocoa is being able to propagate errors along the signal chain and have them show up to the end user but with a return type of `NoError`, any errors are being lost. 
Additionally, that forces the consumer of the extension methods to use `try!` instead of `try` which is stylistic bad and users should be handling errors instead of a crash and burn policy.

`rac_operation` would look better and make more sense like:

```swift
func rac_operation(operation: (context: Context, save: Saver) throws -> Void) -> SignalProducer<Void, Error> {
    return SignalProducer { observer, disposable in
        self.operation { context, saver in 
            do {
                try operation(context: context, save: saver)
                observer.sendCompleted()
            } catch {
                guard let error = error as? Error else {
                    observer.sendCompleted()
                    return
                }
                observer.sendFailed(error)
            }
        }
    }
}
```

Then the consumer of that function can do:

```swift
     self.db.rac_operation { context, save in 
         try context.remove(model)
         save()
     }
```
and any error thrown by the try is caught and relayed by `rac_operation`.

3) Removing the save parameter.

You could remove the need for the save parameter at all and just called save inside `rac_operation` before `observer.sendCompleted`. I'm less tied to that because a user may want to do multiple saves within one operation but to support both you can simply use function overload, one that supports passing the saver and one that doesn't.

**Comment by pepibumur** [comment]
Covered your three improvements here @startupthekid 
https://github.com/pepibumur/SugarRecord/commit/2bcc062c180e1b7afe41c12369df9067096776a3
