### ISSUE TITLE
Context update method

### ISSUE THREAD

**Issue by startupthekid** [pepibumur/SugarRecord#217]
Consider the following scenario:

You retrieve a `Post` model from the network while at the same time retrieving the same from your local database. However, the local post is out of date and the network model has an updated field. So what you need to do is replace the old local model with the new network one. An operation that could look something like:

```swift
let networkModel = ...
self.storage.operation { context, save in
    context.update(networkModel)
}
```

Using Realm as an example, realm uses the `.add` method to add models to the realm with `update = true` flag to indicate if the model is simply an update and then realm intelligently searches based on the primary object key. If no key exists, then it becomes a normal insert.

What I propose is either:

- A new `update` method to be implemented by conformers of `Context`
- In the case of Realm, add the update flag: `self.add(entity as! Object, update: true)`

The second way strikes me as the better one because it prevents inserts of duplicate objects, just updating the same one, and there's still support for doing:

```swift
    self.storage.operation { context, save in
        model.name = "Joseph"
        save()
    } 
```

If that sounds good to you @pepibumur, I'll issue a pull request changing the Realm insert method.

**Comment by Tj3n** [comment]
+1, just figure that this missing this `update` method for Realm, cant understand why Realm have that very convenient method but this doesn't use

**Comment by startupthekid** [comment]
It's been addressed in #218

**Comment by Tj3n** [comment]
Forcing flag `update=true` will cause crash if the Realm Object don't have `Primary key` set

**Comment by startupthekid** [comment]
Again, if you want it changed, issue a PR yourself @Tj3n.
