### ISSUE TITLE
Remove all object in a Realm?

### ISSUE THREAD

**Issue by Tj3n** [pepibumur/SugarRecord#219]
Is there anyway i can easily remove all record from Realm with SugarRecord? As mention in [this SO question](http://stackoverflow.com/questions/26185679/how-can-i-easily-delete-all-objects-in-a-realm), the `removeStore` method only good to call before Realm, but I want to call it in middle of functioning, fetch then remove is not efficent

**Comment by Tj3n** [comment]
I've create a small extension as follow, maybe can @pepibumur can include it in next release

```
extension RealmDefaultStorage {
    public func removeAllRecord() throws {
        let context: Realm = self.saveContext as! Realm
        context.beginWrite()
        context.deleteAll()
        try context.commitWrite()
    }
}
```

**Comment by pepibumur** [comment]
done here 07316e612d72604370c0b4e3d0991a504696846f
