### ISSUE TITLE
Build fails with Carthage in Xcode 7.3

### ISSUE THREAD

**Issue by urazov-s** [pepibumur/SugarRecord#224]
The following build commands failed:
	CompileSwift normal arm64 /Users/urazov/projects/Metrica/Carthage/Checkouts/sugarrecord/SugarRecord/Source/CoreData/Entities/CoreData.swift
	CompileSwift normal arm64 /Users/urazov/projects/Metrica/Carthage/Checkouts/sugarrecord/SugarRecord/Source/CoreData/Entities/ObjectModel.swift
	CompileSwift normal arm64 /Users/urazov/projects/Metrica/Carthage/Checkouts/sugarrecord/SugarRecord/Source/Reactive/ReactiveCocoa/ReactiveStorage+ReactiveCocoa.swift
	CompileSwift normal arm64 /Users/urazov/projects/Metrica/Carthage/Checkouts/sugarrecord/SugarRecord/Source/CoreData/Entities/Store.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)

**Comment by pepibumur** [comment]
This might be related https://github.com/pepibumur/SugarRecord/issues/214

**Comment by pepibumur** [comment]
@urazov-s could you try now?
