### ISSUE TITLE
examples don't compile

### ISSUE THREAD

**Issue by rshev** [pepibumur/SugarRecord#225]
via CocoaPods and here are the errors:
![image](https://cloud.githubusercontent.com/assets/10714746/14421883/cf220556-ffcb-11e5-8ebc-02ae900b61f3.png)

**Comment by pepibumur** [comment]
https://github.com/pepibumur/SugarRecord/commit/2b2efbcf7d77d4dcbc19afefd34a6c5d79b2c5ea
