### ISSUE TITLE
Update Result Dependency

### ISSUE THREAD

**Issue by startupthekid** [pepibumur/SugarRecord#229]
Can you update Result to 2.0.0? ReactiveCocoa 4.1.0 depends on that version.

**Comment by startupthekid** [comment]
And also, Realm to 0.99, ReactiveCocoa to 4.1.0 :)

I'd do it myself but I have so many problems trying to use Carthage. Someday I'll learn.

**Comment by pepibumur** [comment]
hahahah let's say all of them!

**Comment by startupthekid** [comment]
What Swift version is this on, 2.1? If I remember correctly, 2.2 was a minor update, 2.3 would probably cause breaking changes.

**Comment by pepibumur** [comment]
mmm I updated it to the last one. The one with the new fancy selectors. I'm updating all the project external dependencies. Let's see how many things I break down.
