### ISSUE TITLE
Remove default subspecs

### ISSUE THREAD

**Issue by startupthekid** [pepibumur/SugarRecord#230]
To minimize library size, CoreData and realm shouldn't be included as default subspecs. Users should opt in to whatever behavior they need ala `SugarRecord/Realm`

**Comment by pepibumur** [comment]
Good idea, I'll remove it and force the developer to specify the configuration they want manually.

**Comment by startupthekid** [comment]
Woo! Love the library by the way. Especially with Realm, it makes it a lot easier to deal with threading.

**Comment by pepibumur** [comment]
Really? Realm has a really nice interface. I tried to replicate it for CoreData and find a generic interface that could be used in both scenarios.

**Comment by startupthekid** [comment]
Oh don't get me wrong, Realm is awesome. The hard part comes in when you create a Realm, say on the main thread, and then offload updates to a background thread. Realm throws an exception because changes have to be made on the same thread that the realm was made on but with SugarRecord, I don't have to worry about that!

**Comment by pepibumur** [comment]
Oh, I get your point now. Yes, it's kind of encapsulated, and it ensures good practices with the interface. Just execute your operation and save if you want to save your changes. That's all. And if you use Reactive you also have the reactive interface.
