### ISSUE TITLE
App crash when Realm Object does not have primary key

### ISSUE THREAD

**Issue by lamson** [pepibumur/SugarRecord#235]
See this line of code
https://github.com/pepibumur/SugarRecord/blob/master/SugarRecord/Source/Realm/Extensions/Realm.swift#L20

This is an issue. When 'update' flag is 'true', the Realm Object must have a primary key.
On SugarRecord upgrade, if your app has any Realm Object without primary key, it will crash!

**Comment by pepibumur** [comment]
Good catch @lamson . I'll fix it. Thanks for reporting it

**Comment by pepibumur** [comment]
@lamson https://github.com/pepibumur/SugarRecord/commit/46e630406d5ffcef292c5f003e9b41cf66e156dd
