### ISSUE TITLE
Creating new items in scratch context seems overly difficult.

### ISSUE THREAD

**Issue by grangej** [pepibumur/SugarRecord#238]
What is the correct procedure for creating a set of objects in a background saving context ? Then saving said context?

**Comment by grangej** [comment]
The following pattern was what I came up with, but it feels wrong:

`        do {
            
            try self.db?.operation({ [weak self] (context, save) in
                
                self?.savingContext = context
                self?.saveClosure = save
                
                let person: Person = try! context.create()
                
                person.id = NSUUID().UUIDString

                self?.person.value = person.mapEntity()
            })
        }
        catch let error {
            
            print(error)
        }`

**Comment by pepibumur** [comment]
Hey @grangej 
First, you shouldn't save a reference to the context that the operation closure provides you with.  They're meant to be used only in that closure. Regarding the why it's not getting save, it's due to the fact that you don't save the context before returning in the block. That means the save context that was created for your operation gets destroyed and do do your changes as well.

```swift
do {
try self.db?.operation({ [weak self] (context, save) in
            let person: Person = try! context.create()
            person.id = NSUUID().UUIDString
            self?.person.value = person.mapEntity()
            save()
        })
    }
    catch let error {

        print(error)
    }`
```

**Comment by pepibumur** [comment]
Waiting for your feedback to close/review the issue.

**Comment by grangej** [comment]
Amazingly enough it did work, but that I agree it is wrong ;) I believe that by hanging on to strong references to the save block it stays around. 

What I am trying to accomplish is creating an object in a detail view controller , edit said object but be able to still cancel the changes / create. This is why I am creating the object on the background context so if I leave the VC the object will be destroyed. 

I did not see a way of getting a context, creating object in context, and then later saving the context? 

If there is a better way of doing such a pattern I would be open to suggestions. If not I would propose exposing the ability to perform a block from a context with a save block? Similar to how it is done in the underlying CoreData NSManagedObjectContext performBlock / performBlockAndWait. If you like I can contribute a suggestion / make a pull request. 

So to be clear you would be able to do the following :

self.savingContext = db.savingContext

savingContext.operation ({ (save) in 

Create object. Etc. })

....

savingContext.operation ({ (save) in 

Make changes . })

...
savingContext.operation ({ (save) in 

save() })

**Comment by pepibumur** [comment]
@grangej could you make a PR proposal and we evaluate it?

**Comment by grangej** [comment]
@pepibumur I am going to close this one after our conversation , I no longer believe this is the correct approach. Will revisit if necessary.

**Comment by pepibumur** [comment]
Nice, I'm open to suggestions and improvements.
