### ISSUE TITLE
SaveContext does not compute fresh context

### ISSUE THREAD

**Issue by grangej** [pepibumur/SugarRecord#239]
In readme it is stated : 

> SaveContext: Use this context for background operations, the property saveContext of the storage is a computed property so every time you call it you get a new fresh context to be used.

Based on review of code and testing this is not true, is this a problem with the documentation or the implementation? 

In CoreDataDefaultStorage +27 , we are checking for a stored self_saveContext and returning.

**Comment by pepibumur** [comment]
It's a documentation problem. It's not computed every time but instantiated and retained when the stack is initialized. I'll update the documentation.

**Comment by grangej** [comment]
Wouldn't this cause problems if two threads are trying to make changes? Each thread should have its own context no?

**Comment by pepibumur** [comment]
https://github.com/pepibumur/SugarRecord/commit/824ea3d3f076d697d2f1f883f68bca59266b77c9
