### ISSUE TITLE
Try to delete a record with relationship field failed, and then can do nothing

### ISSUE THREAD

**Issue by Talnaj** [pepibumur/SugarRecord#246]
I created a entity named "Category", and a relationship field (one to more) named "things" to entity "Thing", if I want to delete a record that things count >0, that will be failed, and then I can do nothing, all operations will be failed, include create / edit /delete.

How to fix: Restart my app, everything will be well.

By the way, I added the checking function for things field that count must <= 0, but if somewhere I lost the checking function, issue will be raised again.

**Comment by pepibumur** [comment]
@Talnaj what's the deletion rule of your relationship from `Category` to `Things`?
