### ISSUE TITLE
Fix wrong Observable documentation

### ISSUE THREAD

**Issue by grangej** [pepibumur/SugarRecord#247]
According to documentation you should be able to create an observable using the storage class, but there does not appear to be a function observe available in storage.

I am using latest master built from carthage , using:

carthage update --platform iOS --configuration Debug

In the documentation it is : storage.instance.observe(Request<>)

Based on the code it looks to be : CoreDataObservable(Request, Context).observe

**
Fix the documentation, it was wrong.
**

**Comment by pepibumur** [comment]
Did it work @grangej ?

**Comment by grangej** [comment]
Yah, my bad, I am using the generic storage protocol in my app instead of the specific CoreDataDefaultStorage. Although it is observable(Request<T>) not observe(Request<T>) :)

**Comment by grangej** [comment]
Do you have a good example on how you would integrate this into a tableView using rx?

**Comment by pepibumur** [comment]
Not yet. Would you like to contribute with the example project adding an example using observables? You've been actively contributing with issues and ideas to the library. If you would like you I can guide you through it and help you.

**Comment by grangej** [comment]
Sure would be happy too, It would help me to better understand it I am sure. 

Specifically I am wondering how we would maintain sort order?

**Comment by pepibumur** [comment]
https://github.com/pepibumur/SugarRecord/commit/30ddb1dd0ee405bf82834b5fd014204120dc73c0
