### ISSUE TITLE
Carthage build fails

### ISSUE THREAD

**Issue by silvansky** [pepibumur/SugarRecord#248]
Hi! 

I tried to intsall SugarRecord via Carthage, but the buil failed with following message:

    /Users/valentine/Projects/MyProject/Carthage/Checkouts/ExecutionContext/ExecutionContext/ExecutionContext.swift:136:20: error: use of unresolved identifier 'LoopSemaphore'
    A shell task (/usr/bin/xcrun xcodebuild -project /Users/valentine/Projects/MyProject/Carthage/Checkouts/ExecutionContext/ExecutionContext.xcodeproj -scheme ExecutionContext-tvOS -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
I use Xcode 7.3.1.

**Comment by pepibumur** [comment]
@silvansky could you copy & paste your Cartfile? Thanks!

**Comment by silvansky** [comment]
My full cartfile:

        github "crossroadlabs/Express" ~> 0.3
        github "pepibumur/sugarrecord"

**Comment by pepibumur** [comment]
Oh thanks @silvansky , I'l check it out.

**Comment by pepibumur** [comment]
Duplicated https://github.com/pepibumur/SugarRecord/issues/259
