### ISSUE TITLE
Observable / RxSwift.Observable 

### ISSUE THREAD

**Issue by grangej** [pepibumur/SugarRecord#249]
I am getting a crash in the following code:

specifically where we are calling "self.dispose()" 

First question would be are we trying to call SR Dispose? If so who is supposed to override this?

Second question is, calling our class "Observable" is inconvenient, since RxSwift already uses that class name and having to sprinkle RxSwift.Observable everywhere is less than optimal solution. 

How about renaming to **RequestObservable** ?

`public extension Observable {
    
    public func rx_observe() -> RxSwift.Observable<ObservableChange<[T]>> {
        return RxSwift.Observable.create { (observer) -> Disposable in
            self.observe { change in
                observer.onNext(change)
            }
            return AnonymousDisposable {
                self.dispose()
                observer.onCompleted()
            }
        }
    }
    
}
`

The crash is due to : 

`    internal func dispose() {
        assertionFailure("The observe method must be overriden")
    }`

**Comment by pepibumur** [comment]
Good catch @grangej and thanks for the fix. Once you review a couple of comments I added we can merge it and close this issue.
