### ISSUE TITLE
Rename Observable<T: Entity>

### ISSUE THREAD

**Issue by gregpardo** [pepibumur/SugarRecord#252]
This conflicts with regular RxSwift Observable class and forces you to have to specify RxSwift.Observable in any files that use both RxSwift and SugarRecord.

**Comment by grangej** [comment]
Agreed, @pepibumur I can take this up if you approve?

**Comment by pepibumur** [comment]
Go ahead with it @grangej :)

**Comment by pepibumur** [comment]
👏 nice job @grangej
