### ISSUE TITLE
RequestObservable with Sectioned Tableview

### ISSUE THREAD

**Issue by cody1024d** [pepibumur/SugarRecord#261]
Right now I am struggling to see how the RequestObservable properly captures the ability to have sections within a UITableView.  

The problem is within the information passed through the observe closure.  When an insertion, deletion, or update occurs, the closure is only provided with the row from the NSIndexPath, which is not sufficient in determining where the modification actually occurred.  

There are some work arounds that can be done for adds and updates, however, for deletes, which only provide the row which was deleted (and not even the object that was deleted), there is no way to know from which section it was deleted.

As of right now, the only solution I can figure is having to maintain essentially two lists, one which would be a "master" list, which would be used in the delete scenario, to go row -> object.  And then a dictionary to be used as the "sectioned" list, where I maintain the actual "state" of the list.

**Comment by pepibumur** [comment]
Hello @cody1024d 
I understand your concern. The problem with the current design is that it's done to support Realm/CoreData. Although CoreData supports sections, Realm doesn't. Two solutions come to my mind in that regards:
- Use the observable proxy between SugarRecord and Realm to support sections.
- Implement the sections on your side going through the returned objects. But you'd miss the information about which section changed in that case.

Do you have any other idea/thought/proposal? Thanks for reporting it 😛

**Comment by cody1024d** [comment]
Thanks for the quick response @pepibumur!  Looking at the source, I figured Realm was the suspect!  As of right now, I'm maintaining sections within the tableview, although, as you said, it's a bit ugly, and having to refresh the entire table each time is unfortunate.

I would agree, that I think getting the observable proxy to support sections within Realm is probably the best option.  There are some other libraries which may give us a "head start"; specifically: [](https://github.com/redbooth/RealmResultsController/tree/master/Source)

Is this at all on the road map for Sugar Record, or would this be something you'd be open to a pull request for?  I have a work around in place (as per your second solution), although it isn't ideal, and is quite ugly haha

**Comment by cody1024d** [comment]
Also, on a somewhat related note, what is the reasoning behind not having observable being a function on the Storage protocol?  Based on what I can see, it's a public function on the CoreDataDefaultStorage, and on the RealmStorage, but not on the protocol.  This limits my ability to practice protocol-oriented programming, and hinders my ability to mock-out Storage during unit testing

**Comment by pepibumur** [comment]
Hi @cody1024d , you're welcome. I'm very open to PR. Don't worry if it's a bit ugly, I think we can iterate over it and get a mergeable version of your workaround. Regarding the library, I know it, they are friends of mine and worked on that library when Realm didn't support notifications but since Realm supports it natively I decided to use the native solution instead.

Regarding your questions about protocols there was a reason for that but it doesn't come to my mind right now. I fact I started implementing it from the `Storage` abstraction but I ended up moving to the storages implementations. If I find out the reason I'll let you know. Maybe you can find a way to do it with protocols. Feel free to propose changes/improvements, I can add you as a contributor if you're interested in improving the framework :)

**Comment by cody1024d** [comment]
Sounds good!  I'll take a look around and try and PR when I have some time! :)

**Comment by pepibumur** [comment]
Did you checkout the dependencies with Carthage?
```
cartahage update
```

**Comment by cody1024d** [comment]
I did. It ran successfully; that's the strange part!  Here are the exact errors I'm seeing:

```
No such module Reactive Cocoa
```
The above is happening in the file ReactiveStorage+ReactiveCocoa.  The weird part is that I clearly see the ReactiveCocoa.framework inside the linked frameworks and libraries.

```
ditto: can't get real path for source '/Users/Cody/Library/Developer/Xcode/DerivedData/SugarRecord-anyatibiqqjeuobdbrmvtywhndbw/Build/Intermediates/SugarRecord.build/Debug-iphonesimulator/SugarRecord-CoreData-iOS.build/Objects-normal/x86_64/SugarRecordCoreData-Swift.h'
Command /usr/bin/ditto failed with exit code 1
```

```
ld: file not found: /Users/Cody/Library/Developer/Xcode/DerivedData/SugarRecord-anyatibiqqjeuobdbrmvtywhndbw/Build/Intermediates/SugarRecord.build/Debug-iphonesimulator/SugarRecord-CoreData-iOS.build/Objects-normal/x86_64/RequestObservable.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by cody1024d** [comment]
I updated Carthage, and it seems to have resolved my issue.  I'm going to take a look around, and see what I can do about the above issues.
